# Generated by Django 4.2.16 on 2024-09-29 18:11

import api.valida_cpf
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Barraca_Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='festas', to='api.barraca')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa_Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(default='123.456.789-00', max_length=14, validators=[api.valida_cpf.validar_cpf])),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('fechada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao_Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.barraca')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.cartao')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.festa')),
                ('user_barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao_Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('forma_pagamento', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to='api.cartao')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to='api.festa')),
                ('user_caixa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='api.movimentacao_barraca')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('estocavel', models.BooleanField(default=False)),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='api.barraca')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_na_festa', to='api.festa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produto_na_festa', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='api.tipo_produto'),
        ),
        migrations.AddField(
            model_name='movimentacao_produto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_produto', to='api.produto'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='festa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estoques', to='api.festa'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estoques', to='api.produto'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cartoes', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='caixa_festa',
            name='festa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='caixas_festa', to='api.festa'),
        ),
        migrations.AddField(
            model_name='caixa_festa',
            name='user_caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='festas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barraca_festa',
            name='festa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barracas', to='api.festa'),
        ),
        migrations.AddField(
            model_name='barraca_festa',
            name='user_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barracas', to=settings.AUTH_USER_MODEL),
        ),
    ]
