# Generated by Django 5.1 on 2024-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_barraca_barraca_festa_caixa_festa_cartao_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa_festa',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caixa_festa',
            name='iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caixa_festa',
            name='troco_inicial',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixa_festa',
            name='troco_final',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
    ]
