# Generated by Django 4.2.13 on 2024-06-05 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_barraca_colaborador_produto_tipo_produto_delete_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('fechada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='barraca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='api.barraca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produtos', to='api.tipo_produto'),
        ),
        migrations.CreateModel(
            name='Movimentacao_Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to='api.cartao')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to='api.festa')),
                ('user_caixa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao_Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.barraca')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.cartao')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to='api.festa')),
                ('user_barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes_barraca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('data', models.DateField()),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estoques', to='api.festa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estoques', to='api.produto')),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cartoes', to='api.cliente'),
        ),
        migrations.CreateModel(
            name='Caixa_Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='caixas_festa', to='api.festa')),
                ('user_caixa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='festas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barraca_Festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='festas', to='api.barraca')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barracas', to='api.festa')),
                ('user_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barracas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
