# Generated by Django 4.2.13 on 2024-06-07 01:36

import api.valida_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cliente_cpf_alter_colaborador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='12345678900', max_length=11, validators=[api.valida_cpf.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='12345678900', max_length=11, validators=[api.valida_cpf.validar_cpf]),
        ),
    ]
