# Generated by Django 4.2.15 on 2024-08-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_produto_festa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.AlterUniqueTogether(
            name='produto_festa',
            unique_together=set(),
        ),
    ]
